# fly.toml app configuration file generated for whatchadoin on 2023-06-08T10:54:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whatchadoin"
primary_region = "mad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
